version: "3.5"
services:
    # PHP service
    php:
        container_name: laraveljwt_php
        restart: unless-stopped
        build:
            context: "docker/php"
            dockerfile: Dockerfile
            args:
                - INSTALL_GD=${PHP_FPM_INSTALL_GD}
                - INSTALL_COMPRESSION=${PHP_FPM_INSTALL_COMPRESSION}
                - INSTALL_FTP=${PHP_FPM_INSTALL_FTP}
                - INSTALL_MBSTRING=${PHP_FPM_INSTALL_MBSTRING}
                - INSTALL_MCRYPT=${PHP_FPM_INSTALL_MCRYPT}
                - INSTALL_PDO_MYSQL=${PHP_FPM_INSTALL_PDO_MYSQL}
                - INSTALL_PDO_POSTGRESQL=${PHP_FPM_INSTALL_PDO_POSTGRESQL}
                - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
                - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
                - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
                - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
                - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
                - INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER}
                - INSTALL_JSON_XML=${PHP_FPM_INSTALL_JSON_XML}
                - INSTALL_CURL=${PHP_FPM_INSTALL_CURL}
                - INSTALL_OPENSSL=${PHP_FPM_INSTALL_OPENSSL}
                - INSTALL_COMPOSER=${PHP_FPM_INSTALL_COMPOSER}
        expose:
            - "9000"
        ports:
            - 9000:9000
        volumes:
            - ${APPLICATION}:/var/www/html
        networks:
            - code-network

    # Nginx service
    nginx:
        image: nginx:1.19
        container_name: laraveljwt_nginx
        restart: unless-stopped
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        links:
            - php
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - code-network

    # MySQL database service
    db:
        image: mysql:8.0
        container_name: mysql80
        restart: unless-stopped
        command: --explicit_defaults_for_timestamp
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${MYSQL_DATA}:/var/lib/mysql
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
